In [1]:
import numpy as np

In [ ]:
np.array()
np.zeros()
np.ones()
np.arange()
np.linspace()
dtype
np.append()
np.delete()
np.sort()
ndarray.ndim()
ndarray.size()
ndarray.shape()
np.reshape()

In [9]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [8]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.arange(4)

array([0, 1, 2, 3])

In [26]:
np.arange(2,19,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
np.linspace(0,10,5,dtype=int)

array([ 0,  2,  5,  7, 10])

In [32]:
data = np.array([1,2,3])
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

1
2
[1 2]
[2 3]
[2 3]


In [33]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [36]:
print(a[a>3])

[ 4  5  6  7  8  9 10 11 12]


In [37]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [38]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [39]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [40]:
slicing and indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [44]:
array = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr1 = array[3:8]
arr1

array([4, 5, 6, 7, 8])

In [47]:
a1 = np.array([[1, 1],
     [2, 2]])

In [48]:
a2 = np.array([[3, 3],
     [4, 4]])

In [50]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [51]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [52]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.shape()
np.size()

In [59]:
np_arr = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [60]:
np_arr.shape

(3, 4)

In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
# get number of rows in array
num_of_rows2 = np.size(np_arr, 0)
# get number of columns in 2D numpy array
num_of_columns2 = np.size(np_arr, 1)
print('Number of Rows : ', num_of_rows2)
print('Number of Columns : ', num_of_columns2)

Number of Rows :  3
Number of Columns :  4


In [63]:
print('Total number of elements in  array : ', np.size(np_arr))

Total number of elements in  array :  12


In [68]:
data = np.array([[1,2],[3,4]])

In [69]:
data[0,1]
data[1:3]
data[0:2,0]

array([1, 3])

In [70]:
data.max()
data.min()
data.sum()

10

In [71]:
data.max(axis=0)
data.max(axis=1)

array([2, 4])

In [72]:
array = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [73]:
array.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
numpy.random.rand: Generates an array of specified shape containing random values uniformly distributed between 0 and 1.

numpy.random.randn: Generates an array of specified shape containing random values normally distributed with mean 0 and variance 1.

numpy.random.randint: Generates an array of specified shape containing random integers between specified low and high values.

numpy.random.choice: Randomly selects elements from a given array.

numpy.random.shuffle: Shuffles the elements of a given array in place.

numpy.random.seed: Sets the seed for generating random numbers, which allows for reproducibility of results.

numpy.random.permutation: Randomly permutes a sequence of numbers or an array.

numpy.random.normal: Generates an array of specified shape containing random values normally distributed with a specified mean and standard deviation.

numpy.random.uniform: Generates an array of specified shape containing random values uniformly distributed between specified low and high values.

numpy.random.binomial: Generates an array of specified shape containing random values from a binomial distribution with a specified number of trials and probability of success.

In [82]:
np.random.random(15)

array([0.59178271, 0.36864062, 0.42456516, 0.11531001, 0.87264146,
       0.86669594, 0.72516739, 0.33433177, 0.75876411, 0.1991933 ,
       0.23334793, 0.96005079, 0.51481426, 0.24399979, 0.53025886])

In [83]:
np.random.rand(3,2)

array([[0.75347452, 0.9818129 ],
       [0.36884367, 0.20111237],
       [0.63622694, 0.37051958]])

In [84]:
np.random.randn(3,5)

array([[-0.85999504, -0.83087536,  0.70784704, -0.19597023,  1.35411533],
       [ 0.13094829, -0.77113419,  1.02102136,  0.21100352,  1.18152334],
       [-0.53800866, -1.88753029, -0.87519695,  0.7087826 ,  0.74834922]])

In [87]:
a = np.random.randint(1,100,50)

In [86]:
np.random.seed(10)

In [91]:
np.random.choice(a,10)

array([50, 90, 70, 95, 94, 90,  9, 70, 70, 95])

In [94]:
np.random.shuffle(a)

In [95]:
a

array([41, 70, 28, 34, 37, 75, 94, 90, 19, 16, 79, 32, 95, 94, 14, 55, 26,
       10, 37, 17, 14, 31, 74, 78, 12, 63, 29, 65, 89, 66, 55, 52, 30,  1,
       31, 90, 89, 23, 29, 78, 12, 50, 13, 73, 87,  9, 10, 58, 93, 24])

In [103]:
x = np.random.normal(5,1,100)